name: GitHub Actions test Lambda

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configurando NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Instalando Dependencias
        run: cd ./function && npm install

      - name: Rodando tests
        run: cd ./function && npm run unit
        env:
          JWT_SECRET: basic

