name: Terraform AWS

on:
  workflow_run:
    workflows: ["Running lambda tests"]
    types:
      - completed


env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  apply-dev:
    name: 'terraform apply dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'terraform'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.terraform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Apply
        run: terraform apply -auto-approve